import React, { useState } from 'react';
import { TerraformProviderConfig, ManagedResourceType } from '../../shared/types';
import { TERRAFORM_RESOURCE_MAPPINGS } from '../../shared/constants';
import { getRecommendations } from '../../shared/scopes';
import { getAdditionsForVersion } from '../../shared/versions';
import { getOrgInfo, generateVersionsTf, generateVariablesTf, generateProviderTf } from '../../shared/terraform-gen';
import { useStore } from '../hooks/useStore';

interface Props {
  config: TerraformProviderConfig;
  orgUrl: string;
}

function generateTfvars(scopes: string[]): string | null {
  if (scopes.length === 0) return null;
  const scopeList = scopes.map(s => `  "${s}",`).join('\n');
  return `# Generated by Okta Terraform Toolkit
# These are the OAuth scopes needed for your selected resources

okta_scopes = [
${scopeList}
]
`;
}

function generateImportsTf(selectedResources: ManagedResourceType[]): string | null {
  if (selectedResources.length === 0) return null;

  const lines: string[] = [
    '# Import blocks for managed resources',
    '# Replace <RESOURCE_ID> with actual Okta resource IDs',
    '# Run: terraform plan -generate-config-out=generated.tf',
    '',
  ];

  for (const type of selectedResources) {
    const mapping = TERRAFORM_RESOURCE_MAPPINGS.find(m => m.managedType === type);
    if (!mapping) continue;

    lines.push(`# ${mapping.managedType}`);
    lines.push(`# import {`);
    lines.push(`#   to = ${mapping.terraformType}.example`);
    lines.push(`#   id = "<RESOURCE_ID>"`);
    lines.push(`# }`);
    lines.push('');
  }

  return lines.join('\n');
}

// Recommended resource configurations per type
const RESOURCE_CONFIGS: Record<string, string> = {
  users: `# ─── Users ───
# Data source: look up existing users
data "okta_user" "example" {
  search {
    name  = "profile.email"
    value = "user@example.com"
  }
}

# Resource: manage a user
# resource "okta_user" "example" {
#   first_name = "Jane"
#   last_name  = "Doe"
#   login      = "jane.doe@example.com"
#   email      = "jane.doe@example.com"
#   status     = "ACTIVE"
# }

# User group membership
# resource "okta_user_group_memberships" "example" {
#   user_id = okta_user.example.id
#   groups  = [okta_group.example.id]
# }

# Custom user schema property
# resource "okta_user_schema_property" "example" {
#   index  = "custom_attribute"
#   title  = "Custom Attribute"
#   type   = "string"
#   master = "PROFILE_MASTER"
# }
`,

  groups: `# ─── Groups ───
# Data source: look up existing group
data "okta_group" "everyone" {
  name = "Everyone"
}

# Resource: manage a group
# resource "okta_group" "example" {
#   name        = "Engineering"
#   description = "Engineering team"
# }

# Group rule (auto-assign users based on conditions)
# resource "okta_group_rule" "example" {
#   name              = "Auto-assign engineers"
#   status            = "ACTIVE"
#   group_assignments = [okta_group.example.id]
#   expression_value  = "String.stringContains(user.department, \\"Engineering\\")"
# }

# Group membership
# resource "okta_group_memberships" "example" {
#   group_id = okta_group.example.id
#   users    = [okta_user.example.id]
# }
`,

  applications: `# ─── Applications ───
# Data source: look up existing app
# data "okta_app" "example" {
#   label = "My Application"
# }

# OAuth 2.0 / OIDC application
# resource "okta_app_oauth" "example" {
#   label                      = "My OIDC App"
#   type                       = "web"
#   grant_types                = ["authorization_code", "refresh_token"]
#   redirect_uris              = ["https://app.example.com/callback"]
#   post_logout_redirect_uris  = ["https://app.example.com/logout"]
#   response_types             = ["code"]
#   token_endpoint_auth_method = "client_secret_basic"
#   consent_method             = "REQUIRED"
#   lifecycle {
#     ignore_changes = [groups]  # Manage group assignments separately
#   }
# }

# SAML 2.0 application
# resource "okta_app_saml" "example" {
#   label                    = "My SAML App"
#   sso_url                  = "https://app.example.com/sso"
#   recipient                = "https://app.example.com/sso"
#   destination              = "https://app.example.com/sso"
#   audience                 = "https://app.example.com"
#   subject_name_id_template = "${"$"}{user.userName}"
#   subject_name_id_format   = "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
#   signature_algorithm      = "RSA_SHA256"
#   digest_algorithm         = "SHA256"
# }

# App group assignment
# resource "okta_app_group_assignment" "example" {
#   app_id   = okta_app_oauth.example.id
#   group_id = okta_group.example.id
# }

# Group push — pushes Okta group to downstream app (requires provisioning)
# resource "okta_app_group_push_now" "example" {
#   app_id                = okta_app_saml.example.id
#   group_push_id         = "..."  # from okta_app_group_assignments
#   trigger_new_or_update = "trigger"
# }
# Note: Push groups share the /api/v1/apps rate limit bucket.
# Only works on apps with provisioning enabled (SCIM, etc.).
`,

  authServers: `# ─── Authorization Servers ───
# Data source: default auth server
data "okta_auth_server" "default" {
  name = "default"
}

# Custom authorization server
# resource "okta_auth_server" "example" {
#   name        = "My API"
#   description = "Authorization server for my API"
#   audiences   = ["https://api.example.com"]
#   status      = "ACTIVE"
# }

# Auth server policy
# resource "okta_auth_server_policy" "example" {
#   auth_server_id   = okta_auth_server.example.id
#   name             = "Default Policy"
#   description      = "Default access policy"
#   priority         = 1
#   client_whitelist = ["ALL_CLIENTS"]
#   status           = "ACTIVE"
# }

# Auth server scope
# resource "okta_auth_server_scope" "example" {
#   auth_server_id   = okta_auth_server.example.id
#   name             = "api:read"
#   description      = "Read access to API"
#   consent          = "IMPLICIT"
#   metadata_publish = "ALL_CLIENTS"
# }

# Auth server claim
# resource "okta_auth_server_claim" "example" {
#   auth_server_id = okta_auth_server.example.id
#   name           = "groups"
#   value_type     = "GROUPS"
#   group_filter_type = "STARTS_WITH"
#   value          = ""
#   claim_type     = "IDENTITY"
#   scopes         = [okta_auth_server_scope.example.name]
# }
`,

  policies: `# ─── Policies ───
# Sign-on policy
# resource "okta_policy_signon" "example" {
#   name            = "Custom Sign-On Policy"
#   status          = "ACTIVE"
#   description     = "Custom sign-on policy"
#   groups_included = [data.okta_group.everyone.id]
# }

# Sign-on policy rule
# resource "okta_policy_rule_signon" "example" {
#   policy_id          = okta_policy_signon.example.id
#   name               = "MFA Required"
#   status             = "ACTIVE"
#   access             = "ALLOW"
#   mfa_required       = true
#   mfa_prompt         = "ALWAYS"
#   session_idle        = 120
#   session_lifetime    = 720
# }

# Password policy
# resource "okta_policy_password" "example" {
#   name                   = "Custom Password Policy"
#   status                 = "ACTIVE"
#   description            = "Strong password requirements"
#   password_min_length    = 12
#   password_min_uppercase = 1
#   password_min_lowercase = 1
#   password_min_number    = 1
#   password_min_symbol    = 1
#   groups_included        = [data.okta_group.everyone.id]
# }

`,

  idps: `# ─── Identity Providers ───
# OIDC Identity Provider
# resource "okta_idp_oidc" "example" {
#   name                  = "External OIDC Provider"
#   authorization_url     = "https://idp.example.com/authorize"
#   authorization_binding = "HTTP-REDIRECT"
#   token_url             = "https://idp.example.com/token"
#   token_binding         = "HTTP-POST"
#   user_info_url         = "https://idp.example.com/userinfo"
#   user_info_binding     = "HTTP-REDIRECT"
#   jwks_url              = "https://idp.example.com/.well-known/jwks.json"
#   jwks_binding          = "HTTP-REDIRECT"
#   scopes                = ["openid", "profile", "email"]
#   client_id             = var.idp_client_id
#   client_secret         = var.idp_client_secret
#   issuer_url            = "https://idp.example.com"
#   username_template     = "idpuser.email"
#
#   # Single Logout support (v6.7.0+)
#   participate_slo = true
#   slo_url         = "https://idp.example.com/logout"
# }
`,

  authenticators: `# ─── Authenticators ───
# resource "okta_authenticator" "example" {
#   name   = "Custom OTP"
#   key    = "custom_otp"
#   method = "otp"
#   status = "ACTIVE"
# }
`,

  networkZones: `# ─── Network Zones ───
# IP-based network zone
# resource "okta_network_zone" "office" {
#   name     = "Office Network"
#   type     = "IP"
#   gateways = ["203.0.113.0/24"]
#   proxies  = []
#   status   = "ACTIVE"
# }

# Dynamic network zone (location-based)
# resource "okta_network_zone" "us_only" {
#   name              = "US Only"
#   type              = "DYNAMIC"
#   dynamic_locations = ["US"]
#   status            = "ACTIVE"
# }

`,

  trustedOrigins: `# ─── Trusted Origins ───
# resource "okta_trusted_origin" "example" {
#   name   = "App Origin"
#   origin = "https://app.example.com"
#   scopes = ["CORS", "REDIRECT"]
#   active = true
# }
`,

  brands: `# ─── Brands & Themes ───
# data "okta_brands" "all" {}
#
# resource "okta_theme" "example" {
#   brand_id = tolist(data.okta_brands.all.brands)[0].id
#   primary_color_hex         = "#1662DD"
#   secondary_color_hex       = "#FFFFFF"
#   sign_in_page_touch_point_variant = "OKTA_DEFAULT"
# }
`,

  eventHooks: `# ─── Event Hooks ───
# resource "okta_event_hook" "example" {
#   name    = "User Created Hook"
#   events  = ["user.lifecycle.create"]
#   channel = {
#     type    = "HTTP"
#     version = "1.0.0"
#     uri     = "https://hooks.example.com/okta/user-created"
#   }
#   auth = {
#     type  = "HEADER"
#     key   = "Authorization"
#     value = var.webhook_secret
#   }
# }
`,

  inlineHooks: `# ─── Inline Hooks ───
# resource "okta_inline_hook" "example" {
#   name    = "Token Transform"
#   type    = "com.okta.oauth2.tokens.transform"
#   version = "1.0.0"
#   status  = "ACTIVE"
#   channel = {
#     type    = "HTTP"
#     version = "1.0.0"
#     uri     = "https://hooks.example.com/okta/token-transform"
#     method  = "POST"
#   }
# }
`,

  domains: `# ─── Custom Domains ───
# resource "okta_domain" "example" {
#   name = "id.example.com"
# }
#
# resource "okta_domain_certificate" "example" {
#   domain_id   = okta_domain.example.id
#   type        = "PEM"
#   certificate = file("certs/cert.pem")
#   private_key = file("certs/key.pem")
# }
`,

  logStreams: `# ─── Log Streams ───
# resource "okta_log_stream" "example" {
#   name   = "AWS EventBridge Stream"
#   type   = "aws_eventbridge"
#   status = "ACTIVE"
#   settings {
#     account_id = var.aws_account_id
#     region     = "us-east-1"
#     event_source_name = "okta-logs"
#   }
# }
`,

  customRoles: `# ─── Custom Admin Roles ───
# resource "okta_admin_role_custom" "example" {
#   label       = "App Manager"
#   description = "Can manage applications"
#   permissions = [
#     "okta.apps.manage",
#     "okta.apps.assignment.manage",
#   ]
# }
#
# resource "okta_admin_role_custom_assignments" "example" {
#   resource_set_id = okta_resource_set.example.id
#   custom_role_id  = okta_admin_role_custom.example.id
#   members         = [okta_user.admin.id]
# }
`,

  emailDomains: `# ─── Email Domains ───
# resource "okta_email_domain" "example" {
#   brand_id     = tolist(data.okta_brands.all.brands)[0].id
#   domain       = "mail.example.com"
#   display_name = "Example Corp"
#   user_name    = "noreply"
# }
`,

  behaviors: `# ─── Behavior Detection Rules ───
# resource "okta_behavior" "new_device" {
#   name           = "New Device Behavior"
#   type           = "ANOMALOUS_DEVICE"
#   number_of_authentications = 0
#   location_granularity_type = "LAT_LONG"
#   radius_from_location      = 20
#   status         = "ACTIVE"
# }
`,

  captchas: `# ─── CAPTCHA ───
# resource "okta_captcha" "example" {
#   name      = "reCAPTCHA"
#   type      = "HCAPTCHA"
#   site_key  = var.captcha_site_key
#   secret_key = var.captcha_secret_key
# }
#
# resource "okta_captcha_org_wide_settings" "example" {
#   captcha_id = okta_captcha.example.id
#   enabled_for = ["SSO"]
# }
`,

  devices: `# ─── Devices ───
# data "okta_device_assurance_policy" "example" {
#   name = "Any"
# }
#
# Note: Device resources are primarily managed through Okta Verify and
# device trust policies. Terraform manages device assurance policies.
`,

  profileMappings: `# ─── Profile Mappings ───
# data "okta_app" "target" {
#   label = "My App"
# }
#
# resource "okta_profile_mapping" "example" {
#   source_id          = "<okta_user_source_id>"
#   target_id          = data.okta_app.target.id
#   delete_when_absent = true
#
#   mappings {
#     id         = "firstName"
#     expression = "appuser.firstName"
#   }
#   mappings {
#     id         = "lastName"
#     expression = "appuser.lastName"
#   }
# }
`,

  realms: `# ─── Realms ───
# resource "okta_realm" "example" {
#   label       = "Partner Realm"
#   is_default  = false
# }
# Note: Realms require the Realms feature to be enabled on your org.
`,

  features: `# ─── Features ───
# resource "okta_feature" "example" {
#   feature_id = "<feature_id>"
#   status     = "ENABLED"
# }
# Note: Feature flags require Super Admin. Use with caution —
# enabling/disabling features can affect org-wide behavior.
`,

  pushProviders: `# ─── Push Providers ───
# resource "okta_push_provider" "apns" {
#   provider_type  = "APNS"
#   name           = "iOS Push"
#   configuration {
#     key_id      = var.apns_key_id
#     team_id     = var.apns_team_id
#     token_signing_key = var.apns_signing_key
#   }
# }
`,

  orgSettings: `# ─── Org Settings ───
# resource "okta_org_configuration" "main" {
#   company_name = "Example Corp"
#   website      = "https://example.com"
# }
#
# resource "okta_org_support" "main" {
#   extend_by = 1  # Extend support access by 1 day
# }
#
# resource "okta_security_notification_emails" "main" {
#   send_email_for_new_device_enabled        = true
#   send_email_for_factor_enrollment_enabled = true
#   send_email_for_factor_reset_enabled      = true
#   send_email_for_password_changed_enabled  = true
# }

# Rate limiting configuration
# resource "okta_rate_limiting" "main" {
#   login        = "ENFORCE"
#   authorize    = "ENFORCE"
#   communications_enabled = true
# }
#
# resource "okta_principal_rate_limits" "example" {
#   principal_id   = okta_app_oauth.example.id
#   principal_type = "SSWS_TOKEN"
#   default_percentage_limit  = 50
#   default_concurrent_percentage_limit = 50
# }

# API service integration (OAuth for Okta)
# resource "okta_api_service_integration" "example" {
#   name  = "Terraform Service"
#   type  = "oauth_service"
# }
`,

  governance: `# ─── Governance (Okta Identity Governance) ───
# Note: Governance resources require an OIG license.

# Access certification campaign
# resource "okta_campaign" "example" {
#   name        = "Quarterly Access Review"
#   description = "Review all application access"
# }

# Entitlement management
# resource "okta_entitlement" "example" {
#   app_id = okta_app_oauth.example.id
#   name   = "Admin Access"
# }
#
# resource "okta_entitlement_bundle" "example" {
#   name = "Engineering Bundle"
#   entitlement_ids = [okta_entitlement.example.id]
# }

# Access requests
# resource "okta_request_condition" "example" {
#   name = "Manager Approval"
# }
#
# resource "okta_request_sequence" "example" {
#   name = "Standard Approval Flow"
# }
#
# resource "okta_request_setting_organization" "main" {
#   self_service_enabled = true
# }
#
# resource "okta_request_v2" "example" {
#   name        = "Access Request"
#   description = "Request access to resources"
# }
`,
  identitySources: `# ─── Identity Sources ───
# Identity sources allow Okta to source user profiles from external systems (v6.11.0+)

# Data source: look up an existing identity source
# data "okta_identity_source" "example" {
#   id = "<identity_source_id>"
# }

# Resource: manage an identity source
# resource "okta_identity_source" "example" {
#   name = "My Identity Source"
#   type = "SAML2"
#   # protocol and policy settings vary by source type
#   # See: https://registry.terraform.io/providers/okta/okta/latest/docs/resources/identity_source
# }
`,
};

function generateResourcesTf(selectedResources: ManagedResourceType[], providerVersion: string): string | null {
  if (selectedResources.length === 0) return null;

  const sections: string[] = [
    '# Resource configurations for selected Okta resources',
    `# Generated by Okta Terraform Toolkit (v${providerVersion})`,
    '# Uncomment and customize the resources you need.',
    '',
  ];

  // Version-specific additions grouped by resource type
  const additions = getAdditionsForVersion(providerVersion);
  const additionsByType = new Map<string, string[]>();
  for (const a of additions) {
    if (!additionsByType.has(a.type)) additionsByType.set(a.type, []);
    additionsByType.get(a.type)!.push(a.config);
  }

  for (const type of selectedResources) {
    const config = RESOURCE_CONFIGS[type];
    if (config) {
      sections.push(config);
    }
    // Append version-specific resources for this type
    const typeAdditions = additionsByType.get(type);
    if (typeAdditions) {
      sections.push(...typeAdditions);
    }
  }

  return sections.join('\n');
}

type TabId = 'versions' | 'variables' | 'provider' | 'resources' | 'imports' | 'tfvars';

export default function ProviderBlock({ config, orgUrl }: Props) {
  const { selectedResources, operation, terraformAuthMethod, providerVersion, saveTfFile, saveProjectDir } = useStore();
  const [activeTab, setActiveTab] = useState<TabId>('provider');
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState<string | null>(null);

  const authMethod = terraformAuthMethod;
  const recs = selectedResources.length > 0
    ? getRecommendations(selectedResources, operation)
    : null;
  const oauthScopes = recs?.scopes ?? [];

  const resourcesTf = generateResourcesTf(selectedResources, providerVersion);
  const importsTf = generateImportsTf(selectedResources);
  const tfvarsContent = authMethod === 'oauth' ? generateTfvars(oauthScopes) : null;

  const files: Record<TabId, { filename: string; content: string } | null> = {
    versions: { filename: 'versions.tf', content: generateVersionsTf(providerVersion) },
    variables: { filename: 'variables.tf', content: generateVariablesTf(authMethod) },
    provider: { filename: 'provider.tf', content: generateProviderTf(config, orgUrl, authMethod, oauthScopes) },
    resources: resourcesTf ? { filename: 'resources.tf', content: resourcesTf } : null,
    imports: importsTf ? { filename: 'imports.tf', content: importsTf } : null,
    tfvars: tfvarsContent ? { filename: 'terraform.tfvars', content: tfvarsContent } : null,
  };

  const tabs: { id: TabId; label: string }[] = [
    { id: 'versions', label: 'versions.tf' },
    { id: 'variables', label: 'variables.tf' },
    { id: 'provider', label: 'provider.tf' },
    ...(files.resources ? [{ id: 'resources' as TabId, label: 'resources.tf' }] : []),
    ...(files.imports ? [{ id: 'imports' as TabId, label: 'imports.tf' }] : []),
    ...(files.tfvars ? [{ id: 'tfvars' as TabId, label: 'terraform.tfvars' }] : []),
  ];

  const currentFile = files[activeTab];

  const handleCopy = async () => {
    if (!currentFile) return;
    await navigator.clipboard.writeText(currentFile.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveSingle = async () => {
    if (!currentFile) return;
    const filePath = await saveTfFile(currentFile.content);
    if (filePath) {
      setSaved(filePath);
      setTimeout(() => setSaved(null), 3000);
    }
  };

  const handleSaveProject = async () => {
    const projectFiles: Record<string, string> = {};
    for (const file of Object.values(files)) {
      if (file) projectFiles[file.filename] = file.content;
    }
    const dir = await saveProjectDir(projectFiles);
    if (dir) {
      setSaved(dir);
      setTimeout(() => setSaved(null), 4000);
    }
  };

  return (
    <div className="p-5">
      {/* File tabs */}
      <div className="flex gap-1 mb-3 border-b border-gray-200 flex-wrap">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`
              px-3 py-1.5 text-xs font-mono rounded-t-lg transition-colors -mb-px border
              ${activeTab === tab.id
                ? 'bg-gray-900 text-gray-100 border-gray-900'
                : 'bg-gray-50 text-gray-500 border-gray-200 hover:bg-gray-100'}
            `}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Code block */}
      {currentFile && (
        <pre className="bg-gray-900 text-gray-100 rounded-lg p-4 text-sm font-mono overflow-x-auto leading-relaxed max-h-80 overflow-y-auto">
          {currentFile.content}
        </pre>
      )}

      {/* Actions */}
      <div className="flex items-center gap-3 mt-4">
        <button
          onClick={handleCopy}
          className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
        >
          {copied ? 'Copied!' : 'Copy File'}
        </button>
        <button
          onClick={handleSaveSingle}
          className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
        >
          Save File
        </button>
        <button
          onClick={handleSaveProject}
          className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 transition-colors"
        >
          Export Full Project
        </button>
        {saved && (
          <span className="text-sm text-green-600">
            Saved to {saved}
          </span>
        )}
      </div>
    </div>
  );
}
