// AUTO-GENERATED by scripts/update-schema-loader.js — do not edit manually.
// To regenerate: node scripts/update-schema-loader.js
import type { ProviderSchema, ResourceSchema } from './provider-schemas/schema-types';

import schema_raw_6_6_1 from './provider-schemas/6.6.1.json';
import schema_raw_6_7_0 from './provider-schemas/6.7.0.json';
import schema_raw_6_8_0 from './provider-schemas/6.8.0.json';
import schema_raw_6_9_0 from './provider-schemas/6.9.0.json';
import schema_raw_6_10_0 from './provider-schemas/6.10.0.json';
import schema_raw_6_11_0 from './provider-schemas/6.11.0.json';
import schema_raw_6_12_0 from './provider-schemas/6.12.0.json';
import schema_raw_6_13_0 from './provider-schemas/6.13.0.json';
import schema_raw_6_14_0 from './provider-schemas/6.14.0.json';

const SCHEMAS: Record<string, ProviderSchema> = {
  '6.6.1': schema_raw_6_6_1 as unknown as ProviderSchema,
  '6.7.0': schema_raw_6_7_0 as unknown as ProviderSchema,
  '6.8.0': schema_raw_6_8_0 as unknown as ProviderSchema,
  '6.9.0': schema_raw_6_9_0 as unknown as ProviderSchema,
  '6.10.0': schema_raw_6_10_0 as unknown as ProviderSchema,
  '6.11.0': schema_raw_6_11_0 as unknown as ProviderSchema,
  '6.12.0': schema_raw_6_12_0 as unknown as ProviderSchema,
  '6.13.0': schema_raw_6_13_0 as unknown as ProviderSchema,
  '6.14.0': schema_raw_6_14_0 as unknown as ProviderSchema,
};

export function loadSchema(version: string): ProviderSchema {
  const schema = SCHEMAS[version];
  if (!schema) throw new Error(`No schema snapshot for provider version ${version}`);
  return schema;
}

export function getResourceSchema(version: string, resourceType: string): ResourceSchema | null {
  const schema = loadSchema(version);
  return (schema.resource_schemas[resourceType] ?? schema.data_source_schemas[resourceType]) ?? null;
}

export function isKnownResource(version: string, resourceType: string): boolean {
  const schema = loadSchema(version);
  return resourceType in schema.resource_schemas || resourceType in schema.data_source_schemas;
}
