// AUTO-GENERATED by scripts/update-schema-loader.js — do not edit manually.
// To regenerate: node scripts/update-schema-loader.js
import type { ProviderSchema, ResourceSchema } from './provider-schemas/schema-types';

import schema_raw_6_13_0 from './provider-schemas/6.13.0.json';

const SCHEMAS: Record<string, ProviderSchema> = {
  '6.13.0': schema_raw_6_13_0 as unknown as ProviderSchema,
};

export function loadSchema(version: string): ProviderSchema {
  const schema = SCHEMAS[version];
  if (!schema) throw new Error(`No schema snapshot for provider version ${version}`);
  return schema;
}

export function getResourceSchema(version: string, resourceType: string): ResourceSchema | null {
  const schema = loadSchema(version);
  return (schema.resource_schemas[resourceType] ?? schema.data_source_schemas[resourceType]) ?? null;
}

export function isKnownResource(version: string, resourceType: string): boolean {
  const schema = loadSchema(version);
  return resourceType in schema.resource_schemas || resourceType in schema.data_source_schemas;
}
