import { TerraformProviderConfig } from './types';
import { ProviderVersion, getVersionConstraint } from './versions';

export function getOrgInfo(orgUrl: string) {
  const orgName = new URL(orgUrl).hostname.split('.')[0];
  const baseUrl = new URL(orgUrl).hostname.includes('oktapreview')
    ? 'oktapreview.com'
    : 'okta.com';
  return { orgName, baseUrl };
}

export function generateVersionsTf(providerVersion: ProviderVersion): string {
  return `terraform {
  required_version = ">= 1.5.0"

  required_providers {
    okta = {
      source  = "okta/okta"
      version = "${getVersionConstraint(providerVersion)}"
    }
  }
}
`;
}

export function generateVariablesTf(authMethod: 'api_token' | 'oauth'): string {
  if (authMethod === 'oauth') {
    return `variable "okta_client_id" {
  description = "Okta OAuth service app client ID"
  type        = string
}

variable "okta_private_key" {
  description = "Path to the private key PEM file for the Okta service app"
  type        = string
  sensitive   = true
}

variable "okta_scopes" {
  description = "OAuth scopes to request (generated by Okta Terraform Toolkit)"
  type        = list(string)
}
`;
  }
  return `variable "okta_api_token" {
  description = "Okta API token for authentication"
  type        = string
  sensitive   = true
}
`;
}

export function generateProviderTf(
  config: TerraformProviderConfig,
  orgUrl: string,
  authMethod: 'api_token' | 'oauth',
  scopes?: string[]
): string {
  const { orgName, baseUrl } = getOrgInfo(orgUrl);
  const rateLimitBlock = `
  # Rate limit optimization (generated by Okta Terraform Toolkit)
  max_retries      = ${config.max_retries}
  backoff          = ${config.backoff}
  min_wait_seconds = ${config.min_wait_seconds}
  max_wait_seconds = ${config.max_wait_seconds}
  request_timeout  = ${config.request_timeout}
  max_api_capacity = ${config.max_api_capacity}`;

  if (authMethod === 'oauth') {
    const scopeLines = scopes && scopes.length > 0
      ? `  scopes       = var.okta_scopes`
      : `  scopes       = var.okta_scopes`;
    return `provider "okta" {
  org_name     = "${orgName}"
  base_url     = "${baseUrl}"
  client_id    = var.okta_client_id
  private_key  = file(var.okta_private_key)
${scopeLines}
${rateLimitBlock}
}

# Run with: terraform apply -parallelism=${config.parallelism}
`;
  }

  return `provider "okta" {
  org_name     = "${orgName}"
  base_url     = "${baseUrl}"
  api_token    = var.okta_api_token
${rateLimitBlock}
}

# Run with: terraform apply -parallelism=${config.parallelism}
`;
}
