provider "okta" {
  org_name     = "nicole-oie"
  base_url     = "okta.com"
  api_token    = var.okta_api_token

  # Rate limit optimization (generated by Okta Terraform Toolkit)
  max_retries      = 4
  backoff          = true
  min_wait_seconds = 19
  max_wait_seconds = 90
  request_timeout  = 120
  max_api_capacity = 70
}

# Run with: terraform apply -parallelism=4
